### PR TITLE
Use the latest DBDefs.pm file

### PR DESCRIPTION
**Pull request by yvanzo**
<del>Address issue #79 by applying a patch against the latest `DBDefs.pm.sample` file that is pulled down with MusicBrainz server instead of copying the static file `DBDefs.pm`. If the patch gets out-of-sync, it will be known at build time (while trying to apply the patch) rather than at run time (with previous static file).</del>

It just updates the DBDefs.pm with DBDefs.pm.sample v-2018-08-14.

### CODE REVIEW

**Review by jsturgis — COMMENTED** [review]
What do you think of doing a find replace instead of patch? My concern with patch is that as the DBDefs.pm changes we may end up with a conflict when trying to apply the patch.

**Comment by yvanzo** [comment]
I don't mind. A patch conflict is unlikely to arise for nothing, whereas find/replace is more likely to still pass in case of breaking change. In either case, DBDefs.pm.sample change log should be checked manually.

**Comment by yvanzo** [comment]
I removed the commit https://github.com/metabrainz/musicbrainz-docker/commit/4b9e36c8336c8d8e90d8f2b5c7bf19ed46615342 from this pull request, as it doesn’t add much to have a patch instead of a static file. In either case, the small difference about upstream changes is not worth the added complexity.

**Comment by jsturgis** [comment]
ok sounds good thanks.

**Pull request merged**
