### PR TITLE
Allow setting the number of musicbrainz processes

### PR DESCRIPTION
**Pull request by yvanzo**
Add the environment variable `MUSICBRAINZ_SERVER_PROCESSES` to the image for the service `musicbrainz`.  That can be set to a different integer value through a Docker compose override.

```yml
    musicbrainz:
      environment:
        MUSICBRAINZ_SERVER_PROCESSES=3
```

### CODE REVIEW

**Comment by JoshDi** [comment]
@yvanzo I am running a slave replication server. Can you update the readme with a sample override file, location (guessing /local/compose ?) and the respective 'admin/configuration add' command?

Thank you!

**Comment by yvanzo** [comment]
@JoshDi: Thanks to your feedback I just changed base compose files in https://github.com/metabrainz/musicbrainz-docker/pull/174/commits/c4e1fc20f5c49511b47ebf9f729731099774b0b4 to allow setting the variable `MUSICBRAINZ_SERVER_PROCESSES` without requiring any override file. Details are given in the up section “[Docker environment variables](https://github.com/metabrainz/musicbrainz-docker/blob/435e18445dc01e5fc723b2ff755a42ae6dcdc9b2/README.md#docker-environment-variables)”. Is that clear enough?

**Comment by JoshDi** [comment]
> @JoshDi: Thanks to your feedback I just changed base compose files in [c4e1fc2](https://github.com/metabrainz/musicbrainz-docker/commit/c4e1fc20f5c49511b47ebf9f729731099774b0b4) to allow setting the variable `MUSICBRAINZ_SERVER_PROCESSES` without requiring any override file. Details are given in the up section “[Docker environment variables](https://github.com/metabrainz/musicbrainz-docker/blob/435e18445dc01e5fc723b2ff755a42ae6dcdc9b2/README.md#docker-environment-variables)”. Is that clear enough?

Yes, this is very clear. I added **MUSICBRAINZ_SERVER_PROCESSES=10** to my .env file

**Comment by SuperSandro2000** [comment]
Those are not extra processes but extra threads right?

**Comment by yvanzo** [comment]
No, these really are extra `plackup` processes.

Edit: Just clarified this in https://github.com/metabrainz/musicbrainz-docker/pull/174/commits/03ce58a1a35bfef32b88cfa2b090a2457bd5babd.

**Pull request merged**
