### PR TITLE
Follow database schema change 2022 Q2

### PR DESCRIPTION
**Pull request by yvanzo**
- Upgrade to MusicBrainz Server `2022-05-16-schema-change` with database schema sequence `27`
- Upgrade to Search Index Rebuilider (SIR) `3.0.0` for compatibility

Detailed upgrade steps will be provided in release notes.

## Readiness tests

* [ ] Installing a development setup from scratch with live indexing

After the first schema 27 replication packets have been produced:

* [x] Upgrading a full replica with live indexing (yvanzo)
* [ ] Installing a full replica from scratch with live indexing

### CODE REVIEW

**Review by reosarevok — APPROVED** [review]
LGTMBDNT

**Comment by JoshDi** [comment]
Will the sir 3.0.0 upgrade improve slave indexing performance?

**Comment by yvanzo** [comment]
@JoshDi: Absolutely.

**Comment by JoshDi** [comment]
Wow - sir 3.0 is so much faster. Full reindexing took half the time. 

The real win though is that during replication, indexing finishes within an hour instead of taking over 24 hours (aka not finishing the indexing before new replication packets). 

This is a huge win here. Thank you everyone

**Comment by PeterCodar** [comment]
Thanks for that information @JoshDi!

Do you say that if the default replication time is set to run every hour, indexing now finish in a useful manner?

**Comment by JoshDi** [comment]
> Thanks for that information @JoshDi!
> 
> Do you say that if the default replication time is set to run every hour, indexing now finish in a useful manner?

Im running my MusicBrainz slave server on some pretty powerful hardware with many DB, SIR and other memory tweaks. 

That being said, I agree that slave servers can now attempt to run replication hourly, instead of daily, since the live indexing jobs are way more performant compared to SIR 2.x

I just ran another replication packet (for 1 or 2 hrs past the last one). 10k of indexing queues finished within a few minutes, unlike hours in the previous version

**Comment by yvanzo** [comment]
These improvements of live search indexing are mainly to be credited to @ta264. See [SIR 3.0.0 release notes](https://github.com/metabrainz/sir/releases/tag/v3.0.0) for details.

**Pull request merged**
